// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Data;

#nullable disable

namespace SmartHome.Data.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20241122192906_NewSoftDeleteRoom")]
    partial class NewSoftDeleteRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Data.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f20bca37-5510-407a-bc86-8a956a496d02"),
                            DeviceName = "Switch 1",
                            Status = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("a4f4ae0d-b4e4-4fb1-8a20-9d20fb986172"),
                            DeviceName = "Switch 2",
                            Status = false,
                            Type = 1
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Models.DeviceRoom", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("DeviceId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("DevicesRooms");
                });

            modelBuilder.Entity("SmartHome.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a5be361-7399-4f80-8df9-248d35c8c14e"),
                            RoomName = "Kitchen"
                        },
                        new
                        {
                            Id = new Guid("c8805ffb-ff4a-4af4-8647-49c5b3abdf31"),
                            RoomName = "Living Room"
                        },
                        new
                        {
                            Id = new Guid("339e738e-e783-4ff1-b75b-1ecf7f7c634a"),
                            RoomName = "Bathroom"
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Models.DeviceRoom", b =>
                {
                    b.HasOne("SmartHome.Data.Models.Device", "Device")
                        .WithMany("DevicesRooms")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHome.Data.Models.Room", "Room")
                        .WithMany("DevicesRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHome.Data.Models.Device", b =>
                {
                    b.Navigation("DevicesRooms");
                });

            modelBuilder.Entity("SmartHome.Data.Models.Room", b =>
                {
                    b.Navigation("DevicesRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
