// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Data;

#nullable disable

namespace SmartHome.Data.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20241119172157_DeviceToRoom")]
    partial class DeviceToRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Data.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ab5c562-085c-48b0-9434-771fe691f542"),
                            DeviceName = "Switch 1",
                            Status = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("709c7177-e012-4637-9dcf-7a54e29f8338"),
                            DeviceName = "Switch 2",
                            Status = false,
                            Type = 1
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Models.DeviceRoom", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeviceId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("DevicesRooms");
                });

            modelBuilder.Entity("SmartHome.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f207a024-bdf9-4304-b0fe-6b92c598a489"),
                            RoomName = "Kitchen"
                        },
                        new
                        {
                            Id = new Guid("ccb422a0-e8f6-421b-8e53-307b51ff71ed"),
                            RoomName = "Living Room"
                        },
                        new
                        {
                            Id = new Guid("38af0499-bbfa-47b5-915c-5228d7a6458d"),
                            RoomName = "Bathroom"
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Models.DeviceRoom", b =>
                {
                    b.HasOne("SmartHome.Data.Models.Device", "Device")
                        .WithMany("DevicesRooms")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHome.Data.Models.Room", "Room")
                        .WithMany("DevicesRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHome.Data.Models.Device", b =>
                {
                    b.Navigation("DevicesRooms");
                });

            modelBuilder.Entity("SmartHome.Data.Models.Room", b =>
                {
                    b.Navigation("DevicesRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
