// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHome.Data;

#nullable disable

namespace SmartHome.Data.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20241119175610_SeedDeviceRoom")]
    partial class SeedDeviceRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Data.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1292b51a-cf71-4af0-8b0f-c192074c5c71"),
                            DeviceName = "Switch 1",
                            Status = false,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("2cc4e79d-24d6-45a8-99fa-f98e5993368f"),
                            DeviceName = "Switch 2",
                            Status = false,
                            Type = 1
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Models.DeviceRoom", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DeviceId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("DevicesRooms");
                });

            modelBuilder.Entity("SmartHome.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0155568-4a3c-4147-9eb5-a592baa1d7e3"),
                            RoomName = "Kitchen"
                        },
                        new
                        {
                            Id = new Guid("77d03dde-b39b-4a88-a457-10705d62dd45"),
                            RoomName = "Living Room"
                        },
                        new
                        {
                            Id = new Guid("36688ddc-fddb-4f89-9f06-f6ce98e70156"),
                            RoomName = "Bathroom"
                        });
                });

            modelBuilder.Entity("SmartHome.Data.Models.DeviceRoom", b =>
                {
                    b.HasOne("SmartHome.Data.Models.Device", "Device")
                        .WithMany("DevicesRooms")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHome.Data.Models.Room", "Room")
                        .WithMany("DevicesRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SmartHome.Data.Models.Device", b =>
                {
                    b.Navigation("DevicesRooms");
                });

            modelBuilder.Entity("SmartHome.Data.Models.Room", b =>
                {
                    b.Navigation("DevicesRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
